"""empty message

Revision ID: 2022eec5efc4
Revises: 2887d9479642
Create Date: 2019-11-24 14:07:25.874157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2022eec5efc4'
down_revision = '2887d9479642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pessoas', sa.Column('CPF', sa.String(), nullable=True))
    op.add_column('Pessoas', sa.Column('RG', sa.String(), nullable=True))
    op.add_column('Pessoas', sa.Column('telefone', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Pessoas', ['RG'])
    op.create_unique_constraint(None, 'Pessoas', ['CPF'])
    op.create_unique_constraint(None, 'Pessoas', ['telefone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Pessoas', type_='unique')
    op.drop_constraint(None, 'Pessoas', type_='unique')
    op.drop_constraint(None, 'Pessoas', type_='unique')
    op.drop_column('Pessoas', 'telefone')
    op.drop_column('Pessoas', 'RG')
    op.drop_column('Pessoas', 'CPF')
    # ### end Alembic commands ###
