"""empty message

Revision ID: b1103453b191
Revises: 59165b137c86
Create Date: 2019-10-27 14:09:28.510410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1103453b191'
down_revision = '59165b137c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('identificacao', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('idade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificacao'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Membros')
    op.drop_table('capitoes')
    op.add_column('Equipes', sa.Column('capitao', sa.String(), nullable=True))
    op.add_column('Equipes', sa.Column('email', sa.String(), nullable=True))
    op.add_column('Equipes', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('Equipes', sa.Column('país', sa.String(), nullable=True))
    op.add_column('Equipes', sa.Column('site', sa.String(), nullable=True))
    op.add_column('Equipes', sa.Column('slogan', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Equipes', ['email'])
    op.create_unique_constraint(None, 'Equipes', ['slogan'])
    op.create_unique_constraint(None, 'Equipes', ['site'])
    op.drop_column('Equipes', 'professor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Equipes', sa.Column('professor', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'Equipes', type_='unique')
    op.drop_constraint(None, 'Equipes', type_='unique')
    op.drop_constraint(None, 'Equipes', type_='unique')
    op.drop_column('Equipes', 'slogan')
    op.drop_column('Equipes', 'site')
    op.drop_column('Equipes', 'país')
    op.drop_column('Equipes', 'estado')
    op.drop_column('Equipes', 'email')
    op.drop_column('Equipes', 'capitao')
    op.create_table('capitoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('identificacao', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificacao'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Membros',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('identificacao', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('idade', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificacao'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Pessoas')
    # ### end Alembic commands ###
