"""empty message

Revision ID: e83d91893afa
Revises: f7b3a776fa3f
Create Date: 2019-11-24 13:55:19.169502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83d91893afa'
down_revision = 'f7b3a776fa3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Equipes', ['firstname'])
    op.create_unique_constraint(None, 'Equipes', ['lastname'])
    op.create_unique_constraint(None, 'Equipes', ['slogan'])
    op.create_unique_constraint(None, 'Equipes', ['email'])
    op.create_unique_constraint(None, 'Equipes', ['site'])
    op.drop_column('Equipes', 'name')
    op.drop_column('Equipes', 'professor')
    op.drop_column('Pessoas', 'identificacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pessoas', sa.Column('identificacao', sa.VARCHAR(), nullable=True))
    op.add_column('Equipes', sa.Column('professor', sa.VARCHAR(), nullable=True))
    op.add_column('Equipes', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'Equipes', type_='unique')
    op.drop_constraint(None, 'Equipes', type_='unique')
    op.drop_constraint(None, 'Equipes', type_='unique')
    op.drop_constraint(None, 'Equipes', type_='unique')
    op.drop_constraint(None, 'Equipes', type_='unique')
    # ### end Alembic commands ###
